### ISSUE TITLE
Wrong org when using reverse dns group

### ISSUE THREAD

**Issue by mynomoto** [borkdude/deps-infer#3]
I ran the example on readme in this project and got the following results:
```
babashka/fs {:mvn/version "0.0.5"}
clj-kondo/clj-kondo {:mvn/version "2021.09.15"}
org/clojure/clojure {:mvn/version "1.11.0-alpha1"}
org/clojure/tools.cli {:mvn/version "1.0.206"}
seancorfield/depstar {:mvn/version "0.1.6"}
version-clj/version-clj {:mvn/version "2.0.1"}
```
Notice that `org/clojure/clojure` should be `org.clojure/clojure` and in the readme the output is correct. I'm running arch linux, not sure if this could be os specific.

**Comment by borkdude** [comment]
You're right, we should replace "/" in the group name with dots. Seems like a simple fix.
