### ISSUE TITLE
Could warn when multiple different artifacts provide the same namespace.

### ISSUE THREAD

**Issue by mynomoto** [borkdude/deps-infer#5]
I got a strange result where `seancorfield/depstar {:mvn/version "0.1.6"}` was showing always as a dependency. In this case the jar had lots of namespaces included in clojure itself and that was causing it to always show in the results. Removing the jar from my ~/.m2 solved the problem but I guess that a warning could be helpful as this should not happen.

**Comment by borkdude** [comment]
This is an anti-pattern, probably depstar had Clojure AOTed-sourced inside of it.

**Comment by borkdude** [comment]
I agree that a warning on this should be helpful, welcome to add it.

**Comment by mynomoto** [comment]
> This is an anti-pattern, probably depstar had Clojure AOTed-sourced inside of it.

Agreed, that should always be a mistake.

> I agree that a warning on this should be helpful, welcome to add it.

Ok, will do.

**Comment by mynomoto** [comment]
There is a use case where the conflict can happen, when the user creates a fork. Before tools.deps people usually pushed the new version to clojars to make easier for people to use. Also when artifacts change names. I still think that this is useful, only adding this for context.

**Comment by mynomoto** [comment]
This was fixed by #9
